'use client';
import {useEffect,useRef,useState} from 'react';
import {queueOfflineSale,getOfflineSales,removeOfflineSale} from './offline-sales';
import {Button} from '@/components/ui/button';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {Switch} from '@/components/ui/switch';
import {Skeleton} from '@/components/ui/skeleton';
import {IceCreamBowl,ShoppingBag,Search,Plus,Minus,Trash2,RefreshCw,Download,Package} from 'lucide-react';
type Product={id:string;sku:string;name:string;category:string;size:string;price:number;stock:number;reorder:number;active:number;image?:string;version:number};
type Line=Product&{quantity:number;percent:number};
const peso=(c:number)=>new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP'}).format(c/100);
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Manila'});
const blankProduct={sku:'',name:'',category:'HERSHEY',size:'8oz',price:0,stock:0,reorder:10,active:1} as Product;
async function api(body?:any){const r=await fetch('/api/pos',{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,cache:'no-store'});const data:any=await r.json();if(!r.ok)throw Object.assign(new Error(data.error||'Could not complete the request.'),{status:r.status});return data;}
function Choice({label,value,onChange,options}:any){return <label className="field"><span>{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map((s:string)=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select></label>}
function Field({label,...props}:any){return <label className="field"><span>{label}</span><input {...props}/></label>}
function Grid({headers,rows}:{headers:string[];rows:any[][]}){return <Table><TableHeader><TableRow>{headers.map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.length?rows.map((r,i)=><TableRow key={i}>{r.map((c,j)=><TableCell key={j}>{c}</TableCell>)}</TableRow>):<TableRow><TableCell colSpan={headers.length}>No records in this view.</TableCell></TableRow>}</TableBody></Table>}
export default function Pos({displayName}:{displayName:string}){
 const [data,setData]=useState<any>(null),[view,setView]=useState('New sale'),[category,setCategory]=useState('All'),[search,setSearch]=useState('');
 const [cart,setCart]=useState<Line[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[online,setOnline]=useState(true),[time,setTime]=useState('');
 const [payment,setPayment]=useState('Cash'),[received,setReceived]=useState(''),[extra,setExtra]=useState('0'),[discountType,setDiscountType]=useState('None'),[customerName,setCustomerName]=useState(''),[customerId,setCustomerId]=useState('');
 const [receipt,setReceipt]=useState<any>(null),[editor,setEditor]=useState<Product|null>(null),[picture,setPicture]=useState<File|null>(null),[deleteTarget,setDeleteTarget]=useState<Product|null>(null),[cancelOrder,setCancelOrder]=useState(false);
 const [stockProduct,setStockProduct]=useState<Product|null>(null),[adjustment,setAdjustment]=useState(''),[remarks,setRemarks]=useState(''),[history,setHistory]=useState<any[]>([]);
 const [from,setFrom]=useState(today),[through,setThrough]=useState(today),[report,setReport]=useState<any>(null),[reportTab,setReportTab]=useState('Transactions');
 const [members,setMembers]=useState<any[]>([]),[member,setMember]=useState<any>(null),[settings,setSettings]=useState<any>(null),[install,setInstall]=useState<any>(null),[installHelp,setInstallHelp]=useState(false),[uncertain,setUncertain]=useState(false),[offlineCount,setOfflineCount]=useState(0);
 const orderId=useRef(''),pending=useRef<any>(null),saving=useRef(false),draftKey=useRef(''),currentUserId=useRef('');
 const isAdmin=data?.user.role==='Admin',products:Product[]=data?.products||[];
 const refresh=async()=>{const d=await api();setData(d);return d;};
 const refreshOfflineCount=async(userId:string)=>setOfflineCount((await getOfflineSales(userId)).length);
 const syncOfflineSales=async(userId:string)=>{const rows=await getOfflineSales(userId);for(const row of rows){try{await api(row.body);await removeOfflineSale(row.id)}catch{break}}await refreshOfflineCount(userId);};
 const run=async(fn:()=>Promise<void>)=>{if(saving.current)return;saving.current=true;setBusy(true);setError('');setNotice('');try{await fn()}catch(e){setError((e as Error).message)}finally{saving.current=false;setBusy(false)}};
 useEffect(()=>{refresh().then(d=>{currentUserId.current=d.user.user_id;refreshOfflineCount(d.user.user_id).catch(()=>{});if(navigator.onLine)syncOfflineSales(d.user.user_id).then(()=>refresh()).catch(()=>{});draftKey.current='miguelitos-pending:'+d.user.user_id;const raw=sessionStorage.getItem(draftKey.current);if(raw){const saved=JSON.parse(raw);pending.current=saved.body;orderId.current=saved.body.id;setCart(saved.cart);setPayment(saved.body.payment);setReceived(String(saved.body.received/100));setExtra(String(saved.body.discount/100));setDiscountType(saved.body.discountType||'None');setCustomerName(saved.body.customerName);setCustomerId(saved.body.customerId);setUncertain(true);setNotice('An interrupted order was recovered. Retry it to confirm its saved status.');}}).catch(e=>setError(e.message));orderId.current=crypto.randomUUID();const tick=()=>setTime(new Date().toLocaleString('en-PH',{timeZone:'Asia/Manila',dateStyle:'medium',timeStyle:'medium'}));tick();const timer=setInterval(tick,1000);const sync=()=>{const connected=navigator.onLine;setOnline(connected);if(connected&&currentUserId.current)syncOfflineSales(currentUserId.current).then(()=>refresh()).catch(()=>{})};sync();window.addEventListener('online',sync);window.addEventListener('offline',sync);const handler=(e:Event)=>{e.preventDefault();setInstall(e)};window.addEventListener('beforeinstallprompt',handler);navigator.serviceWorker?.register('/sw.js').catch(()=>{});return()=>{clearInterval(timer);window.removeEventListener('online',sync);window.removeEventListener('offline',sync);window.removeEventListener('beforeinstallprompt',handler)}},[]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const abort=new AbortController();Promise.resolve(context.registerTool({name:'search_pos_products',description:'Search the catalog. Does not add to cart or record a sale.',inputSchema:{type:'object',properties:{query:{type:'string',maxLength:100}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:any)=>{if(typeof input?.query!=='string'||input.query.length>100)throw Error('Enter a search query up to 100 characters.');setSearch(input.query);setCategory('All');setView('New sale');return {query:input.query}}},{signal:abort.signal})).catch(()=>{});return()=>abort.abort()},[]);
 useEffect(()=>{if(!data)return;if(view==='Reports'||view==='Dashboard')run(async()=>{setReport(await api({action:'reports',from:view==='Dashboard'?today():from,to:view==='Dashboard'?today():through}))});if(view==='Users')run(async()=>setMembers((await api({action:'members'})).rows));if(view==='Settings')setSettings({...data.settings});},[view]);
 const subtotal=cart.reduce((s,i)=>s+i.price*i.quantity,0),itemDiscount=cart.reduce((s,i)=>s+Math.round(i.price*i.quantity*i.percent/10000),0),extraCents=Math.round(Number(extra)*100)||0,discount=itemDiscount+extraCents,tax=Math.round((subtotal-discount)*(data?.settings.tax||0)/10000),total=subtotal-discount+tax;
 const filtered=products.filter(p=>(view!=='New sale'||p.active)&&(category==='All'||p.category===category)&&`${p.name} ${p.sku} ${p.size}`.toLowerCase().includes(search.toLowerCase()));
 const add=(p:Product)=>{if(busy||uncertain)return;const found=cart.find(i=>i.id===p.id);if((found?.quantity||0)>=p.stock){setError('Not enough stock for '+p.name);return}setCart(found?cart.map(i=>i.id===p.id?{...i,quantity:i.quantity+1}:i):[...cart,{...p,quantity:1,percent:0}]);};
 const change=(id:string,key:string,value:number)=>setCart(old=>old.map(i=>i.id===id?{...i,[key]:value}:i));
 const clear=()=>{try{sessionStorage.removeItem(draftKey.current)}catch{}setCart([]);setExtra('0');setReceived('');setDiscountType('None');setCustomerName('');setCustomerId('');pending.current=null;orderId.current=crypto.randomUUID();setUncertain(false)};
 const pay=()=>run(async()=>{if(!cart.length)return;if(payment==='Cash'&&Math.round(Number(received)*100)<total)throw Error('Cash received is insufficient.');if(!pending.current)pending.current={action:'checkout',id:orderId.current,items:cart.map(i=>({id:i.id,quantity:i.quantity,percent:i.percent,price:i.price})),discount:extraCents,payment,received:Math.round(Number(received)*100),discountType:discountType==='None'?'':discountType,customerName,customerId};try{sessionStorage.setItem(draftKey.current,JSON.stringify({body:pending.current,cart}))}catch{throw Error('Allow session storage before recording a sale, so interrupted payments can be recovered.')}if(!online){if(!currentUserId.current)throw Error('User session is not ready.');await queueOfflineSale({id:pending.current.id,userId:currentUserId.current,body:pending.current,queuedAt:new Date().toISOString()});await refreshOfflineCount(currentUserId.current);setData((old:any)=>({...old,products:old.products.map((p:Product)=>{const line=cart.find(i=>i.id===p.id);return line?{...p,stock:p.stock-line.quantity}:p})}));clear();setNotice('Sale saved offline - pending sync.');return}let result;try{result=await api(pending.current)}catch(e:any){if(e.status===400){pending.current=null;sessionStorage.removeItem(draftKey.current);setUncertain(false)}else setUncertain(true);throw e}setReceipt(result.sale);clear();setNotice('Sale saved.');await refresh()});
 const saveProduct=()=>run(async()=>{if(!editor)return;const result=await api({action:'product',product:editor});if(picture){try{const uploaded=await fetch('/api/picture?id='+encodeURIComponent(result.id),{method:'POST',headers:{'Content-Type':picture.type},body:picture});const info:any=await uploaded.json();if(!uploaded.ok)throw Error(info.error)}catch(e){const d=await refresh();setEditor(d.products.find((p:Product)=>p.id===result.id));throw Error('Product saved, but picture was not uploaded. '+(e as Error).message)}}setEditor(null);setPicture(null);await refresh();setNotice('Product saved.');});
 const openProduct=(p:Product)=>{setEditor({...p});setPicture(null)};
 const showReceipt=(id:string)=>run(async()=>setReceipt((await api({action:'receipt',id})).sale));
 const navigation=isAdmin?['New sale','Dashboard','Products','Inventory','Reports','Users','Settings']:['New sale'];
 return <div className="pos-app"><header className="brand"><img src="/logo.png" width="58" height="58" alt="Miguelitos Ice Cream"/><div style={{textAlign:'center'}}>
  <strong>MIGUELITOS</strong>
  <small>ICE CREAM - POS</small>
  {data?.settings?.tin&&<small>TIN: {data.settings.tin}</small>}
</div><div className="account"><span>{data?.user.name||displayName}</span><small>{data?.user.role||'Signing in'}</small><a href="/api/auth/logout" target="_top">Sign out</a></div></header>
 <div className="topline"><span className={online?'connection':'offline'}>{online?'Online':'Offline - sales will sync later'}{offlineCount>0?` - ${offlineCount} pending`:''}</span><time>{time} - Manila</time><Button variant="outline" size="sm" onClick={()=>install?install.prompt():setInstallHelp(true)}><Download size={16}/> Install</Button><Button aria-label="Refresh products" variant="ghost" disabled={busy} onClick={()=>run(async()=>{await refresh();setNotice('Products refreshed.')})}><RefreshCw size={18}/></Button></div>
 <Tabs value={view} onValueChange={v=>{setView(v);setSearch('');setCategory('All');setError('');setNotice('')}} className="main-tabs"><TabsList>{navigation.map(n=><TabsTrigger key={n} value={n}>{n}</TabsTrigger>)}</TabsList></Tabs>
 {error&&<div role="alert" className="message error">{error}{!data&&<Button onClick={()=>run(async()=>{await refresh()})}>Retry</Button>}</div>}{notice&&<div role="status" className="message success">{notice}</div>}
 {!data?<main className="page"><h1>Opening your POS...</h1><Skeleton className="h-48 w-full"/></main>:<>
 {view==='New sale'&&<main className="workspace"><section className="catalog"><div className="section-heading"><div><p className="eyebrow">MIGUELITOS ICE CREAM</p><h1>New sale</h1></div>{isAdmin&&<Button variant="outline" onClick={()=>openProduct({...blankProduct})}><Plus size={18}/> Add product</Button>}</div><label className="search"><Search size={20}/><input aria-label="Search products" placeholder="Search products or SKU" value={search} onChange={e=>setSearch(e.target.value)}/></label><Tabs value={category} onValueChange={setCategory}><TabsList className="category-tabs">{['All',...new Set(products.filter(p=>p.active).map(p=>p.category).filter(Boolean))].map(c=><TabsTrigger key={c} value={c}>{c}</TabsTrigger>)}</TabsList></Tabs>
 <div className="product-grid">{filtered.map(p=><button className="product-card" key={p.id} onClick={()=>add(p)} disabled={!p.stock||busy||uncertain}><div className="product-picture">{p.image?<img src={'/api/picture?id='+encodeURIComponent(p.id)+'&v='+p.version} alt={p.name} loading="lazy"/>:<IceCreamBowl size={52}/>}<span className={p.stock<=p.reorder?'stock low':'stock'}>{p.stock?`${p.stock} left`:'Sold out'}</span></div><div className="product-info"><strong>{p.name}</strong><span>{p.size}</span><div><b>{peso(p.price)}</b><Plus size={18}/></div></div></button>)}</div>
 {!filtered.length&&<div className="empty-state"><img className="welcome-photo" src="/icecream.jpg" alt="Vanilla ice cream cone"/><h2>{products.length?'No matching products':'Your first scoop starts here'}</h2><p>{products.length?'Try another search or category.':'Add your products, prices, pictures, and opening stock to start selling.'}</p>{isAdmin&&!products.length&&<Button onClick={()=>openProduct({...blankProduct})}><Plus/> Add your first product</Button>}<small className="photo-credit">Photo: <a href="https://commons.wikimedia.org/wiki/File:Vanilla_Ice_Cream_Cone_at_Camp_Manitoulin.jpg" target="_blank" rel="noreferrer">Steven Depolo</a> - <a href="https://creativecommons.org/licenses/by/2.0/" target="_blank" rel="noreferrer">CC BY 2.0</a></small></div>}</section>
 <aside className="checkout"><div className="section-heading"><h2><ShoppingBag size={22}/> Current order</h2><span className="badge">{cart.reduce((s,i)=>s+i.quantity,0)} items</span></div>{!cart.length&&<div className="empty-state"><ShoppingBag size={44}/><p>Tap a product to add it to the order.</p></div>}
 <fieldset disabled={busy||uncertain} className="cart-lines">{cart.map(i=><div className="cart-line" key={i.id}><div className="line-heading"><div><strong>{i.name}</strong><small>{i.size} - {peso(i.price)}</small></div><Button size="icon" variant="ghost" aria-label={'Remove '+i.name} onClick={()=>setCart(cart.filter(x=>x.id!==i.id))}><Trash2 size={16}/></Button></div><div className="line-controls"><div className="quantity"><Button size="icon" variant="outline" aria-label={'Decrease '+i.name} disabled={i.quantity<=1} onClick={()=>change(i.id,'quantity',i.quantity-1)}><Minus size={14}/></Button><input type="number" min="1" max={i.stock} aria-label={'Quantity for '+i.name} value={i.quantity} onChange={e=>change(i.id,'quantity',Number(e.target.value))}/><Button size="icon" variant="outline" aria-label={'Increase '+i.name} disabled={i.quantity>=i.stock} onClick={()=>change(i.id,'quantity',i.quantity+1)}><Plus size={14}/></Button></div><label className="item-discount">Discount %<input type="number" min="0" max="100" step="0.01" value={i.percent/100} onChange={e=>change(i.id,'percent',Math.round(Number(e.target.value)*100))}/></label><b>{peso(i.price*i.quantity-Math.round(i.price*i.quantity*i.percent/10000))}</b></div></div>)}</fieldset>
 {cart.length>0&&<><fieldset disabled={busy||uncertain} className="payment-fields"><Field label="Additional discount (PHP)" type="number" min="0" step="0.01" value={extra} onChange={(e:any)=>setExtra(e.target.value)}/><Choice label="Payment" options={['Cash','GCash','Card']} value={payment} onChange={setPayment}/>{payment==='Cash'&&<Field label="Cash received (PHP)" type="number" min="0" step="0.01" value={received} onChange={(e:any)=>setReceived(e.target.value)}/>}</fieldset><div className="summary-line"><span>Subtotal</span><b>{peso(subtotal)}</b></div><div className="summary-line"><span>Discount</span><b>-{peso(discount)}</b></div><div className="summary-line"><span>Tax ({data.settings.tax/100}%)</span><b>{peso(tax)}</b></div><div className="total"><span>Total</span><strong>{peso(total)}</strong></div>{payment==='Cash'&&<div className="summary-line"><span>Change</span><b>{peso(Math.max(0,Math.round(Number(received)*100)-total))}</b></div>}
 <fieldset disabled={busy||uncertain} className="discount-details"><Choice label="Discount recipient" options={['None','PWD','Senior Citizen']} value={discountType} onChange={setDiscountType}/>{(itemDiscount>0||discountType!=='None')&&<><Field label="Full name" value={customerName} onChange={(e:any)=>setCustomerName(e.target.value)} maxLength={180}/><Field label="ID number" value={customerId} onChange={(e:any)=>setCustomerId(e.target.value)} maxLength={80}/><p className="hint">Name, ID, and discount type appear at the bottom of the receipt.</p></>}</fieldset>
 {uncertain&&<p className="message error">The connection was interrupted. Retry this same order to confirm whether it was saved. Do not start another sale for the same customer.</p>}<Button className="pay-button" disabled={busy||total<0} onClick={pay}>{busy?'Saving...':uncertain?'Retry / confirm saved sale':`Record ${payment} sale - ${peso(total)}`}</Button><p className="hint">Records the payment you collected. GCash and card payments must be completed separately.</p><Button className="cancel-button" variant="ghost" disabled={busy||uncertain} onClick={()=>setCancelOrder(true)}>Cancel order</Button></>}
 </aside></main>}
 {view==='Dashboard'&&<main className="page"><h1>Welcome, {data.user.name}</h1><p className="hint">Today in Manila</p><div className="stats">{[["Today's sales",peso((report?.rows||[]).reduce((s:number,r:any)=>s+r.total,0))],["Today's transactions",report?.rows?.length||0],['Active products',products.filter(p=>p.active).length],['Low stock products',products.filter(p=>p.active&&p.stock<=p.reorder).length]].map(([label,value])=><section key={label} className="stat"><span>{label}</span><strong>{value}</strong></section>)}</div><Button onClick={()=>setView('New sale')}>Start a new sale</Button></main>}
 {(view==='Products'||view==='Inventory')&&<main className="page"><div className="section-heading"><h1>{view}</h1>{view==='Products'&&<Button onClick={()=>openProduct({...blankProduct})}><Plus/> Add product</Button>}</div><label className="search"><Search/><input aria-label="Search inventory" placeholder="Search name or SKU" value={search} onChange={e=>setSearch(e.target.value)}/></label><Grid headers={['Product','Size','Price','Stock','Status','Actions']} rows={filtered.map(p=>[<div className="product-label" key={p.id}>{p.image?<img src={'/api/picture?id='+encodeURIComponent(p.id)+'&v='+p.version} alt=""/>:<Package size={24}/>}<div><strong>{p.name}</strong><small>{p.sku} - {p.category}</small></div></div>,p.size,peso(p.price),<span className={p.stock<=p.reorder?'low':''} key="stock">{p.stock}</span>,p.active?'Active':'Inactive',<div className="actions" key="actions">{view==='Products'?<><Button variant="outline" onClick={()=>openProduct(p)}>Edit</Button><Button variant="ghost" onClick={()=>setDeleteTarget(p)} aria-label={'Delete '+p.name}><Trash2 size={18}/></Button></>:<Button variant="outline" onClick={()=>run(async()=>{setStockProduct(p);setAdjustment('');setRemarks('');setHistory((await api({action:'history',id:p.id})).rows)})}>Adjust / history</Button>}</div>])}/></main>}
 {view==='Reports'&&<main className="page"><h1>Sales reports</h1><div className="report-controls"><Field label="From" type="date" value={from} onChange={(e:any)=>setFrom(e.target.value)}/><Field label="Through" type="date" value={through} onChange={(e:any)=>setThrough(e.target.value)}/><Button disabled={busy} onClick={()=>run(async()=>setReport(await api({action:'reports',from,to:through})))}>Apply range</Button><Button variant="outline" disabled={busy} onClick={()=>run(async()=>{setFrom(today());setThrough(today());setReport(await api({action:'reports',from:today(),to:today()}))})}>Today</Button></div><Tabs value={reportTab} onValueChange={setReportTab}><TabsList>{['Transactions','Best sellers','Cone / Cup counts','Other items'].map(t=><TabsTrigger key={t} value={t}>{t}</TabsTrigger>)}</TabsList></Tabs>{report&&<><div className="report-summary"><strong>Total sales: {peso(report.rows.reduce((s:number,r:any)=>s+r.total,0))}</strong><span>{report.rows.length} transactions</span>{['Cash','GCash','Card'].map(p=><span key={p}>{p}: {peso(report.rows.filter((r:any)=>r.payment===p).reduce((s:number,r:any)=>s+r.total,0))}</span>)}</div>{reportTab==='Transactions'&&<Grid headers={['Receipt','Date / time','Cashier','Payment','Total','View']} rows={report.rows.map((r:any)=>[r.receipt,new Date(r.date).toLocaleString('en-PH',{timeZone:'Asia/Manila'}),r.cashier,r.payment,peso(r.total),<Button key={r.id} variant="outline" onClick={()=>showReceipt(r.id)}>Receipt</Button>])}/>} {reportTab==='Best sellers'&&<Grid headers={['Product','Quantity','Net item sales']} rows={report.best.map((r:any)=>[r.name,r.quantity,peso(r.revenue)])}/>} {reportTab==='Cone / Cup counts'&&<><p className="hint">CRUNCHIES counts as Vanilla. Counts use the product details saved with each sale.</p><Grid headers={['Flavor','Cone','8oz','12oz','Total']} rows={[...report.counts.map((r:any)=>[r.flavor,r.Cone,r['8oz'],r['12oz'],r.total]),['TOTAL',...['Cone','8oz','12oz','total'].map(k=>report.counts.reduce((s:number,r:any)=>s+r[k],0))]]}/><h2 className="count-total">TOTAL COUNT = {report.total}</h2><p>{report.other.reduce((s:number,r:any)=>s+r.quantity,0)} other / unclassified items are shown in Other items.</p></>} {reportTab==='Other items'&&<Grid headers={['Product','Category','Size','Quantity']} rows={report.other.map((r:any)=>[r.name,r.category,r.size,r.quantity])}/>}</>}</main>}
{view==='Users'&&<main className="page"><div className="section-heading"><h1>User accounts</h1><Button onClick={()=>setMember({username:'',password:'',name:'',role:'Cashier',active:1})}><Plus/> Add user</Button></div><p className="hint">Each user signs in with their own username and password. Admins can create, edit, deactivate, or reset user passwords here.</p><Grid headers={['Name','Username','Role','Status','Edit']} rows={members.map(m=>[m.name,m.username||'Not set',m.role,m.active?'Active':'Inactive',<Button key={m.user_id||m.name} variant="outline" onClick={()=>setMember({...m,password:'',existing:true})}>Edit</Button>])}/></main>}
 {view==='Settings'&&settings&&<main className="page settings"><h1>Store settings</h1><form onSubmit={e=>{e.preventDefault();run(async()=>{await api({action:'settings',settings});await refresh();setNotice('Settings saved.')})}}>{[['name','Store name'],['address','Address'],['contact','Contact'],['tin','TIN'],['footer','Receipt footer']].map(([key,label])=><Field key={key} label={label} value={settings[key]} maxLength={key==='address'||key==='footer'?500:180} onChange={(e:any)=>setSettings({...settings,[key]:e.target.value})}/>)}<Field label="Tax (%)" type="number" min="0" max="100" step="0.01" value={settings.tax/100} onChange={(e:any)=>setSettings({...settings,tax:Math.round(Number(e.target.value)*100)})}/><Button disabled={busy}>Save settings</Button></form></main>}
 </>}
 <Dialog open={!!editor} onOpenChange={open=>{if(!open&&!busy)setEditor(null)}}><DialogContent className="form-dialog">{error&&<p role="alert" className="message error">{error}</p>}<DialogHeader><DialogTitle>{editor?.id?'Edit product':'Add product'}</DialogTitle><DialogDescription>Save the product and its picture for all POS devices.</DialogDescription></DialogHeader>{editor&&<form onSubmit={e=>{e.preventDefault();saveProduct()}}><fieldset disabled={busy}><div className="form-grid">{[['sku','SKU'],['name','Product name'],['category','Category'],['size','Size (Cone, 8oz, 12oz)']].map(([key,label])=><Field key={key} label={label} required value={(editor as any)[key]} maxLength={180} onChange={(e:any)=>setEditor({...editor,[key]:e.target.value})}/>)}<Field label="Price (PHP)" required type="number" min="0" step="0.01" value={editor.price/100} onChange={(e:any)=>setEditor({...editor,price:Math.round(Number(e.target.value)*100)})}/>{[['stock','Stock'],['reorder','Low-stock level']].map(([key,label])=><Field key={key} label={label} type="number" min="0" max="1000000" step="1" required value={(editor as any)[key]} onChange={(e:any)=>setEditor({...editor,[key]:Number(e.target.value)})}/>)}</div><label className="switch-field"><Switch checked={!!editor.active} onCheckedChange={v=>setEditor({...editor,active:v?1:0})}/> Active product</label><Field label="Product picture (PNG / JPG, up to 5 MB)" type="file" accept="image/png,image/jpeg" onChange={(e:any)=>{const f=e.target.files?.[0];if(f&&f.size>5*1024*1024){setError('Choose a picture under 5 MB.');e.target.value='';return}setPicture(f||null)}}/><Button type="submit" disabled={!online}>{busy?'Saving...':'Save product'}</Button></fieldset></form>}</DialogContent></Dialog>
 <Dialog open={!!stockProduct} onOpenChange={open=>{if(!open&&!busy)setStockProduct(null)}}><DialogContent className="form-dialog wide-dialog">{error&&<p role="alert" className="message error">{error}</p>}<DialogHeader><DialogTitle>Inventory - {stockProduct?.name}</DialogTitle><DialogDescription>Add stock with a positive quantity; subtract with a negative quantity.</DialogDescription></DialogHeader><form className="form-grid" onSubmit={e=>{e.preventDefault();run(async()=>{await api({action:'stock',id:stockProduct?.id,quantity:Number(adjustment),remarks});await refresh();setHistory((await api({action:'history',id:stockProduct?.id})).rows);setAdjustment('');setRemarks('');setNotice('Stock updated.')})}}><Field label="Quantity adjustment" type="number" step="1" required value={adjustment} onChange={(e:any)=>setAdjustment(e.target.value)}/><Field label="Reason" required value={remarks} onChange={(e:any)=>setRemarks(e.target.value)}/><Button disabled={busy}>Save adjustment</Button></form><Grid headers={['Date','Type','Quantity','Staff','Reason']} rows={history.map(r=>[new Date(r.date).toLocaleString('en-PH',{timeZone:'Asia/Manila'}),r.type,r.quantity,r.user,r.remarks])}/></DialogContent></Dialog>
<Dialog open={!!member} onOpenChange={open=>{if(!open&&!busy)setMember(null)}}><DialogContent className="form-dialog">{error&&<p role="alert" className="message error">{error}</p>}<DialogHeader><DialogTitle>{member?.existing?'Edit user':'Add user'}</DialogTitle><DialogDescription>{member?.existing?'Change the username, role, status, or enter a new password to reset it. Leave password blank to keep the current password.':'Create a username and password for this POS user.'}</DialogDescription></DialogHeader>{member&&<form onSubmit={e=>{e.preventDefault();run(async()=>{await api({action:'member',...member});setMembers((await api({action:'members'})).rows);setMember(null);setNotice('User account saved.')})}}><Field label="Username" required autoComplete="off" minLength={3} maxLength={32} value={member.username||''} onChange={(e:any)=>setMember({...member,username:e.target.value})}/><Field label={member.existing?'New password (leave blank to keep current)':'Password'} type="password" required={!member.existing} autoComplete="new-password" minLength={8} maxLength={128} value={member.password||''} onChange={(e:any)=>setMember({...member,password:e.target.value})}/><Field label="Name" required value={member.name} onChange={(e:any)=>setMember({...member,name:e.target.value})}/><Choice label="Role" options={['Cashier','Admin']} value={member.role} onChange={(role:string)=>setMember({...member,role})}/><label className="switch-field"><Switch checked={!!member.active} onCheckedChange={v=>setMember({...member,active:v?1:0})}/> Active account</label><Button disabled={busy}>Save user</Button></form>}</DialogContent></Dialog>
 <Dialog open={!!receipt} onOpenChange={open=>{if(!open)setReceipt(null)}}><DialogContent className="form-dialog receipt-dialog"><DialogHeader><DialogTitle>Sale receipt</DialogTitle><DialogDescription>{receipt?.receipt}</DialogDescription></DialogHeader><pre className="receipt-paper">{receipt?.receipt_text}</pre><Button onClick={()=>window.print()}>Print receipt</Button><p className="hint">Uses your device's print options. Printer support depends on the device.</p></DialogContent></Dialog>
 <Dialog open={installHelp} onOpenChange={setInstallHelp}><DialogContent><DialogHeader><DialogTitle>Install Miguelitos POS</DialogTitle><DialogDescription>Open this POS link in your phone's browser.</DialogDescription></DialogHeader><p><strong>Android:</strong> In Chrome's menu, choose Install app or Add to Home Screen.</p><p><strong>iPhone / iPad:</strong> In Safari, tap Share then Add to Home Screen.</p><p><strong>PC:</strong> Use the install icon in Chrome or Edge when available.</p><p>Internet and an authorized account are required to save sales.</p></DialogContent></Dialog>
 <AlertDialog open={!!deleteTarget} onOpenChange={open=>{if(!open)setDeleteTarget(null)}}><AlertDialogContent><AlertDialogTitle>Remove {deleteTarget?.name}?</AlertDialogTitle><AlertDialogDescription>Products with sales or stock history will be deactivated so their records stay available.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Keep product</AlertDialogCancel><AlertDialogAction onClick={()=>run(async()=>{const result=await api({action:'delete',id:deleteTarget?.id});setDeleteTarget(null);await refresh();setNotice(result.message)})}>Remove product</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <AlertDialog open={cancelOrder} onOpenChange={setCancelOrder}><AlertDialogContent><AlertDialogTitle>Cancel this unsaved order?</AlertDialogTitle><AlertDialogDescription>The items and discount details will be cleared.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Keep order</AlertDialogCancel><AlertDialogAction onClick={clear}>Cancel order</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>;
}



















