import {sqliteTable,text,integer,index,check} from 'drizzle-orm/sqlite-core';
import {sql} from 'drizzle-orm';
export const members=sqliteTable('members',{email:text('email').primaryKey(),userId:text('user_id').unique(),name:text('name').notNull(),role:text('role').notNull(),active:integer('active').notNull().default(1)});
export const products=sqliteTable('products',{id:text('id').primaryKey(),sku:text('sku').notNull().unique(),name:text('name').notNull(),category:text('category').notNull().default(''),size:text('size').notNull().default('Regular'),price:integer('price').notNull(),stock:integer('stock').notNull(),reorder:integer('reorder').notNull().default(10),active:integer('active').notNull().default(1),image:text('image'),version:integer('version').notNull().default(1)},t=>[check('stock_nonnegative',sql`${t.stock}>=0`),check('price_nonnegative',sql`${t.price}>=0`)]);
export const settings=sqliteTable('settings',{id:integer('id').primaryKey(),name:text('name').notNull(),address:text('address').notNull().default(''),contact:text('contact').notNull().default(''),tax:integer('tax').notNull().default(0),footer:text('footer').notNull()});
export const sales=sqliteTable('sales',{id:text('id').primaryKey(),receipt:text('receipt').notNull().unique(),date:text('date').notNull(),cashier:text('cashier').notNull(),cashierEmail:text('cashier_email').notNull(),subtotal:integer('subtotal').notNull(),discount:integer('discount').notNull(),tax:integer('tax').notNull(),total:integer('total').notNull(),payment:text('payment').notNull(),received:integer('received').notNull(),change:integer('change_amount').notNull(),discountType:text('discount_type').notNull().default(''),customerName:text('customer_name').notNull().default(''),customerId:text('customer_id').notNull().default(''),receiptText:text('receipt_text').notNull(),requestHash:text('request_hash').notNull()},t=>[index('sales_date').on(t.date)]);
export const items=sqliteTable('items',{id:text('id').primaryKey(),saleId:text('sale_id').notNull().references(()=>sales.id),productId:text('product_id').notNull().references(()=>products.id),name:text('name').notNull(),category:text('category').notNull().default(''),size:text('size').notNull(),quantity:integer('quantity').notNull(),price:integer('price').notNull(),percent:integer('percent').notNull(),discount:integer('discount').notNull(),net:integer('net').notNull()});
export const movements=sqliteTable('movements',{id:text('id').primaryKey(),productId:text('product_id').notNull().references(()=>products.id),type:text('type').notNull(),quantity:integer('quantity').notNull(),date:text('date').notNull(),user:text('user').notNull(),remarks:text('remarks').notNull()},t=>[index('movements_product').on(t.productId)]);
export const guards=sqliteTable('guards',{id:text('id').primaryKey(),ok:integer('ok').notNull()},t=>[check('transaction_validation',sql`${t.ok}=1`)]);

